import { describe, expect, it } from "vitest";
import { validateSubmission } from "../src/index";
import { validateModeration } from "../src/admin";

const validSubmission = {
  quoteText: "The obstacle is the way.",
  author: "Marcus Aurelius",
  category: "Stoicism",
  tags: ["wisdom", "resilience"],
  installationId: "123e4567-e89b-42d3-a456-426614174000",
  appVersion: "1.3.2"
};

describe("validateSubmission", () => {
  it("normalizes valid fields and removes duplicate tags", () => {
    const result = validateSubmission({
      ...validSubmission,
      quoteText: "  The obstacle   is the way.  ",
      tags: ["Wisdom", " wisdom "]
    });

    expect(result).toEqual({
      ok: true,
      value: {
        ...validSubmission,
        quoteText: "The obstacle is the way.",
        tags: ["Wisdom"]
      }
    });
  });

  it("rejects missing quote text", () => {
    const result = validateSubmission({ ...validSubmission, quoteText: "" });
    expect(result).toEqual({
      ok: false,
      message: "quoteText must contain between 3 and 500 characters."
    });
  });

  it("rejects identifiers that are not UUIDs", () => {
    const result = validateSubmission({ ...validSubmission, installationId: "device-123" });
    expect(result).toEqual({
      ok: false,
      message: "installationId must be a UUID generated by the app."
    });
  });

  it("rejects more than eight tags", () => {
    const result = validateSubmission({
      ...validSubmission,
      tags: Array.from({ length: 9 }, (_, index) => `tag-${index}`)
    });
    expect(result).toEqual({
      ok: false,
      message: "tags must be an array containing at most 8 items."
    });
  });
});

describe("validateModeration", () => {
  it("accepts an edited approval", () => {
    const result = validateModeration({
      action: "approve",
      quoteText: "An edited community quote.",
      author: "Community Author",
      category: "Wisdom",
      tags: ["wisdom", "Wisdom", "community"],
      note: "Checked attribution"
    });

    expect(result).toEqual({
      ok: true,
      value: {
        action: "approve",
        quoteText: "An edited community quote.",
        author: "Community Author",
        category: "Wisdom",
        tags: ["wisdom", "community"],
        note: "Checked attribution"
      }
    });
  });

  it("rejects unsupported moderation actions", () => {
    expect(validateModeration({ action: "delete" })).toEqual({
      ok: false,
      message: "action must be approve or reject."
    });
  });
});
