import { handleAdmin } from "./admin";
import { privacyPage } from "./privacy";

export interface Env {
  DB: D1Database;
  RATE_LIMIT_SALT: string;
  ALLOWED_ORIGIN?: string;
  ACCESS_TEAM_DOMAIN?: string;
  ACCESS_AUD?: string;
}

interface Submission {
  quoteText: string;
  author: string;
  category: string;
  tags: string[];
  installationId: string;
  appVersion?: string;
}

type ValidationResult =
  | { ok: true; value: Submission }
  | { ok: false; message: string };

const MAX_BODY_LENGTH = 16_384;
const INSTALLATION_LIMIT = 5;
const IP_LIMIT = 20;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function validateSubmission(input: unknown): ValidationResult {
  if (input === null || typeof input !== "object" || Array.isArray(input)) {
    return invalid("The request body must be a JSON object.");
  }

  const body = input as Record<string, unknown>;
  const quoteText = cleanText(body.quoteText);
  const author = cleanText(body.author);
  const category = cleanText(body.category);
  const installationId = typeof body.installationId === "string" ? body.installationId.trim() : "";
  const appVersion = body.appVersion === undefined ? undefined : cleanText(body.appVersion);

  if (quoteText.length < 3 || quoteText.length > 500) {
    return invalid("quoteText must contain between 3 and 500 characters.");
  }
  if (author.length > 100) {
    return invalid("author must not exceed 100 characters.");
  }
  if (category.length < 1 || category.length > 50) {
    return invalid("category must contain between 1 and 50 characters.");
  }
  if (!UUID_PATTERN.test(installationId)) {
    return invalid("installationId must be a UUID generated by the app.");
  }
  if (appVersion !== undefined && (appVersion.length < 1 || appVersion.length > 30)) {
    return invalid("appVersion must contain between 1 and 30 characters.");
  }
  if (!Array.isArray(body.tags) || body.tags.length > 8) {
    return invalid("tags must be an array containing at most 8 items.");
  }

  const tags: string[] = [];
  const seenTags = new Set<string>();
  for (const value of body.tags) {
    const tag = cleanText(value);
    if (tag.length < 1 || tag.length > 30) {
      return invalid("Each tag must contain between 1 and 30 characters.");
    }
    const key = tag.toLocaleLowerCase("en-US");
    if (!seenTags.has(key)) {
      seenTags.add(key);
      tags.push(tag);
    }
  }

  return {
    ok: true,
    value: { quoteText, author, category, tags, installationId, appVersion }
  };
}

function invalid(message: string): ValidationResult {
  return { ok: false, message };
}

function cleanText(value: unknown): string {
  return typeof value === "string" ? value.trim().replace(/\s+/g, " ") : "";
}

function normalizeForComparison(value: string): string {
  return value.normalize("NFKC").toLocaleLowerCase("en-US");
}

async function hash(value: string): Promise<string> {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
}

function corsHeaders(request: Request, env: Env): Record<string, string> {
  const origin = request.headers.get("Origin");
  if (!origin || !env.ALLOWED_ORIGIN || origin !== env.ALLOWED_ORIGIN) {
    return {};
  }
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin"
  };
}

function json(request: Request, env: Env, body: unknown, status = 200): Response {
  return Response.json(body, {
    status,
    headers: {
      ...corsHeaders(request, env),
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff"
    }
  });
}

function landingPage(): Response {
  return new Response(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Quote Submission API</title>
  <style>
    :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
    body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #17131f; color: #f1eafd; }
    main { width: min(34rem, calc(100% - 3rem)); padding: 2rem; border: 1px solid #50445f; border-radius: 1.5rem; background: #211a2b; }
    small { color: #bda8d5; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; }
    h1 { margin: .65rem 0; font-size: clamp(2rem, 8vw, 3.5rem); line-height: 1; }
    p { color: #d1c5df; line-height: 1.6; }
    a { color: #d8baff; }
    .status { display: flex; align-items: center; gap: .6rem; margin-top: 1.5rem; font-weight: 700; }
    .dot { width: .7rem; height: .7rem; border-radius: 50%; background: #82d6a3; box-shadow: 0 0 1rem #82d6a3; }
  </style>
</head>
<body>
  <main>
    <small>Quote backend</small>
    <h1>Submission API</h1>
    <p>The quote submission service is deployed and ready to receive moderated submissions from the Android app.</p>
    <p>The private review dashboard is protected by Cloudflare Access.</p>
    <p><a href="/privacy">Privacy & submission policy</a></p>
    <div class="status"><span class="dot"></span>Service online</div>
  </main>
</body>
</html>`, {
    headers: {
      "Content-Type": "text/html; charset=UTF-8",
      "Cache-Control": "public, max-age=300",
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"
    }
  });
}

async function submit(request: Request, env: Env): Promise<Response> {
  if (!request.headers.get("Content-Type")?.toLowerCase().startsWith("application/json")) {
    return json(request, env, { error: "Content-Type must be application/json." }, 415);
  }

  const declaredLength = Number(request.headers.get("Content-Length") ?? 0);
  if (declaredLength > MAX_BODY_LENGTH) {
    return json(request, env, { error: "Request body is too large." }, 413);
  }

  const rawBody = await request.text();
  if (rawBody.length > MAX_BODY_LENGTH) {
    return json(request, env, { error: "Request body is too large." }, 413);
  }

  let input: unknown;
  try {
    input = JSON.parse(rawBody);
  } catch {
    return json(request, env, { error: "Request body contains invalid JSON." }, 400);
  }

  const validation = validateSubmission(input);
  if (!validation.ok) {
    return json(request, env, { error: validation.message }, 400);
  }

  if (!env.RATE_LIMIT_SALT) {
    console.error("RATE_LIMIT_SALT is not configured");
    return json(request, env, { error: "Service is temporarily unavailable." }, 503);
  }

  const submission = validation.value;
  const clientIp = request.headers.get("CF-Connecting-IP") ?? "unknown";
  const [installationHash, ipHash, contentHash] = await Promise.all([
    hash(`${env.RATE_LIMIT_SALT}:installation:${submission.installationId}`),
    hash(`${env.RATE_LIMIT_SALT}:ip:${clientIp}`),
    hash(`${normalizeForComparison(submission.quoteText)}\n${normalizeForComparison(submission.author)}`)
  ]);

  const duplicate = await env.DB.prepare(
    "SELECT id, status FROM submissions WHERE content_hash = ? LIMIT 1"
  ).bind(contentHash).first<{ id: string; status: string }>();
  if (duplicate) {
    return json(request, env, { error: "This quote has already been submitted." }, 409);
  }

  const [installationCount, ipCount] = await Promise.all([
    env.DB.prepare(
      "SELECT COUNT(*) AS count FROM submissions WHERE installation_hash = ? AND submitted_at >= unixepoch() - 86400"
    ).bind(installationHash).first<{ count: number }>(),
    env.DB.prepare(
      "SELECT COUNT(*) AS count FROM submissions WHERE ip_hash = ? AND submitted_at >= unixepoch() - 86400"
    ).bind(ipHash).first<{ count: number }>()
  ]);

  if ((installationCount?.count ?? 0) >= INSTALLATION_LIMIT || (ipCount?.count ?? 0) >= IP_LIMIT) {
    return json(request, env, { error: "Submission limit reached. Please try again tomorrow." }, 429);
  }

  const id = crypto.randomUUID();
  try {
    await env.DB.prepare(
      `INSERT INTO submissions (
        id, quote_text, normalized_text, author, category, tags_json, content_hash,
        installation_hash, ip_hash, app_version
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).bind(
      id,
      submission.quoteText,
      normalizeForComparison(submission.quoteText),
      submission.author,
      submission.category,
      JSON.stringify(submission.tags),
      contentHash,
      installationHash,
      ipHash,
      submission.appVersion ?? null
    ).run();
  } catch (error) {
    if (String(error).includes("UNIQUE constraint failed")) {
      return json(request, env, { error: "This quote has already been submitted." }, 409);
    }
    throw error;
  }

  return json(request, env, { id, status: "pending" }, 201);
}

async function communityUpdates(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const afterValue = url.searchParams.get("after") ?? "0";
  if (!/^\d+$/.test(afterValue)) {
    return json(request, env, { error: "after must be a non-negative revision." }, 400);
  }
  const after = Number(afterValue);
  if (!Number.isSafeInteger(after)) {
    return json(request, env, { error: "after must be a non-negative revision." }, 400);
  }

  const state = await env.DB.prepare("SELECT revision FROM sync_state WHERE id = 1")
    .first<{ revision: number }>();
  const currentRevision = state?.revision ?? 0;
  const etag = `"community-${currentRevision}"`;
  if (after >= currentRevision && request.headers.get("If-None-Match") === etag) {
    return new Response(null, { status: 304, headers: { ETag: etag, "Cache-Control": "public, max-age=60" } });
  }

  const result = await env.DB.prepare(
    `SELECT id, quote_text AS quoteText, author, category, tags_json AS tagsJson,
      revision, active, published_at AS publishedAt
     FROM community_quotes WHERE revision > ? ORDER BY revision LIMIT 501`
  ).bind(after).all<{
    id: string;
    quoteText: string;
    author: string;
    category: string;
    tagsJson: string;
    revision: number;
    active: number;
    publishedAt: number;
  }>();

  const rows = result.results.slice(0, 500);
  const hasMore = result.results.length > rows.length;
  const revision = rows.length > 0 ? rows[rows.length - 1].revision : currentRevision;
  return Response.json({
    revision,
    currentRevision,
    hasMore,
    quotes: rows.filter(row => row.active === 1).map(row => ({
      id: row.id,
      text: row.quoteText,
      author: row.author,
      category: row.category,
      tags: JSON.parse(row.tagsJson),
      revision: row.revision,
      publishedAt: row.publishedAt
    })),
    deletedIds: rows.filter(row => row.active === 0).map(row => row.id)
  }, {
    headers: {
      ETag: etag,
      "Cache-Control": "public, max-age=60",
      "X-Content-Type-Options": "nosniff"
    }
  });
}

async function submissionStatus(request: Request, env: Env, id: string): Promise<Response> {
  if (!UUID_PATTERN.test(id)) return json(request, env, { error: "Not found." }, 404);
  const installationId = request.headers.get("X-Installation-Id")?.trim() ?? "";
  if (!UUID_PATTERN.test(installationId)) {
    return json(request, env, { error: "X-Installation-Id must be a valid UUID." }, 400);
  }
  if (!env.RATE_LIMIT_SALT) return json(request, env, { error: "Service is temporarily unavailable." }, 503);

  const installationHash = await hash(`${env.RATE_LIMIT_SALT}:installation:${installationId}`);
  const status = await env.DB.prepare(
    `SELECT s.status, s.reviewed_at AS reviewedAt, c.id AS communityQuoteId
     FROM submissions s LEFT JOIN community_quotes c ON c.submission_id = s.id
     WHERE s.id = ? AND s.installation_hash = ? LIMIT 1`
  ).bind(id, installationHash).first<{
    status: string;
    reviewedAt: number | null;
    communityQuoteId: string | null;
  }>();
  if (!status) return json(request, env, { error: "Not found." }, 404);
  return json(request, env, status);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/admin" || url.pathname.startsWith("/admin/")) {
      try {
        return await handleAdmin(request, env);
      } catch (error) {
        console.error("Admin request failed", error);
        return json(request, env, { error: "Internal server error." }, 500);
      }
    }

    if (url.pathname === "/" && request.method === "GET") {
      return landingPage();
    }

    if (url.pathname === "/health" && request.method === "GET") {
      return json(request, env, { status: "ok" });
    }

    if (url.pathname === "/privacy" && request.method === "GET") {
      return privacyPage();
    }

    if (url.pathname === "/api/community/quotes") {
      if (request.method !== "GET") {
        const response = json(request, env, { error: "Method not allowed." }, 405);
        response.headers.set("Allow", "GET");
        return response;
      }
      try {
        return await communityUpdates(request, env);
      } catch (error) {
        console.error("Community update request failed", error);
        return json(request, env, { error: "Internal server error." }, 500);
      }
    }

    const statusMatch = url.pathname.match(/^\/api\/submissions\/([0-9a-f-]+)\/status$/i);
    if (statusMatch) {
      if (request.method !== "GET") {
        const response = json(request, env, { error: "Method not allowed." }, 405);
        response.headers.set("Allow", "GET");
        return response;
      }
      try {
        return await submissionStatus(request, env, statusMatch[1]);
      } catch (error) {
        console.error("Submission status request failed", error);
        return json(request, env, { error: "Internal server error." }, 500);
      }
    }

    if (url.pathname !== "/api/submissions") {
      return json(request, env, { error: "Not found." }, 404);
    }

    if (request.method === "OPTIONS") {
      const headers = corsHeaders(request, env);
      return Object.keys(headers).length > 0
        ? new Response(null, { status: 204, headers })
        : json(request, env, { error: "Origin is not allowed." }, 403);
    }

    if (request.method !== "POST") {
      const response = json(request, env, { error: "Method not allowed." }, 405);
      response.headers.set("Allow", "POST, OPTIONS");
      return response;
    }

    try {
      return await submit(request, env);
    } catch (error) {
      console.error("Submission failed", error);
      return json(request, env, { error: "Internal server error." }, 500);
    }
  }
} satisfies ExportedHandler<Env>;
