package app.brokoli5191.quote.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import app.brokoli5191.quote.data.QuoteLanguage

val LocalAppLanguage = staticCompositionLocalOf { QuoteLanguage.ENGLISH }

private val germanUi = mapOf(
    "Daily" to "Heute",
    "Daily Quote" to "Zitat des Tages",
    "Today" to "Heute",
    "A thought worth keeping" to "Ein Gedanke, den es zu bewahren lohnt",
    "Library" to "Bibliothek",
    "Saved" to "Gespeichert",
    "Settings" to "Einstellungen",
    "Your Collection" to "Deine Sammlung",
    "Favorites" to "Favoriten",
    "My Quotes" to "Meine Quotes",
    "App Theme" to "App-Design",
    "System" to "System",
    "Light" to "Hell",
    "Dark" to "Dunkel",
    "AMOLED Pure Black" to "AMOLED Tiefschwarz",
    "Accent Palette" to "Akzentpalette",
    "Quote Sources" to "Quote-Quellen",
    "All" to "Alle",
    "Curated" to "Kuratiert",
    "Community" to "Community",
    "Language" to "Sprache",
    "English" to "Englisch",
    "German" to "Deutsch",
    "Anonymous reflections" to "Autorlose Gedanken",
    "Show original poetic quotes without an author" to "Eigene poetische Quotes ohne Autor anzeigen",
    "Daily Reflection Reminders" to "Tägliche Erinnerungen",
    "Inspirational Mornings" to "Inspirierende Morgen",
    "Choose Notification Time" to "Uhrzeit auswählen",
    "Performance" to "Leistung",
    "Blur Navigation Surfaces" to "Navigation weichzeichnen",
    "Low Performance Mode" to "Energiesparmodus",
    "Updates" to "Updates",
    "Automatic Updates" to "Automatische Updates",
    "Check" to "Prüfen",
    "Download" to "Herunterladen",
    "Install" to "Installieren",
    "Backup & Restore" to "Sicherung & Wiederherstellung",
    "Export" to "Exportieren",
    "Restore" to "Wiederherstellen",
    "Developer Options" to "Entwickleroptionen",
    "Debug & testing tools" to "Debug- und Testwerkzeuge",
    "Select Categories" to "Kategorien auswählen",
    "Clear All" to "Alle löschen",
    "Apply Filter" to "Filter anwenden",
    "Clear Filter" to "Filter löschen",
    "Search quotes, authors, or tags" to "Quotes, Autoren oder Tags suchen",
    "Search results" to "Suchergebnisse",
    "Search Off Icon" to "Keine Suchergebnisse",
    "No Community Quotes Yet" to "Noch keine Community-Quotes",
    "No Wisdom Matches" to "Keine passenden Quotes",
    "Checking for newly approved community quotes..." to "Neue freigegebene Community-Quotes werden gesucht …",
    "Sync again" to "Erneut synchronisieren",
    "Reset All Filters" to "Alle Filter zurücksetzen",
    "Share Wisdom" to "Quote teilen",
    "Explore this author" to "Diesen Autor entdecken",
    "Syncing quotes..." to "Quotes werden synchronisiert …",
    "Try again" to "Erneut versuchen",
    "Save" to "Speichern",
    "No community quotes yet" to "Noch keine Community-Quotes",
    "No quotes available" to "Keine Quotes verfügbar",
    "Approved community quotes will appear here after the next sync." to "Freigegebene Community-Quotes erscheinen nach der nächsten Synchronisierung hier.",
    "Try syncing again in a moment." to "Versuche die Synchronisierung gleich noch einmal.",
    "New quote" to "Neues Quote",
    "Saved privately on this device" to "Privat auf diesem Gerät gespeichert",
    "Quote or affirmation" to "Quote oder Affirmation",
    "Write a quote…" to "Schreibe ein Quote …",
    "Author" to "Autor",
    "Unknown" to "Unbekannt",
    "Shelf" to "Kategorie",
    "Tags" to "Tags",
    "Separate tags with commas" to "Tags mit Kommas trennen",
    "wisdom, courage, morning" to "weisheit, mut, morgen",
    "Add to My Quotes" to "Zu meinen Quotes hinzufügen",
    "Privacy & submission policy" to "Datenschutz- und Einreichungsrichtlinie",
    "No favorites yet" to "Noch keine Favoriten",
    "No custom quotes yet" to "Noch keine eigenen Quotes",
    "Submit for review?" to "Zur Prüfung einreichen?",
    "This quote, its author, category, and tags will be sent to Quote for review. If approved, it may be included in the public quote collection." to "Dieses Quote wird zusammen mit Autor, Kategorie und Tags zur Prüfung gesendet. Nach der Freigabe kann es in die öffentliche Sammlung aufgenommen werden.",
    "Cancel" to "Abbrechen",
    "Submit" to "Einreichen",
    "Submitting..." to "Wird eingereicht …",
    "Submit for review" to "Zur Prüfung einreichen",
    "Pending review" to "Prüfung ausstehend",
    "Approved for community" to "Für die Community freigegeben",
    "Not approved" to "Nicht freigegeben",
    "Customize Widget" to "Widget anpassen",
    "Create Widget" to "Widget erstellen",
    "Drag elements to move" to "Elemente zum Verschieben ziehen",
    "Live Preview" to "Live-Vorschau",
    "Visible Elements" to "Sichtbare Elemente",
    "Decorative Icon" to "Dekoratives Symbol",
    "Quote Label" to "Quote-Beschriftung",
    "Background Blur" to "Hintergrund weichzeichnen",
    "Visual Widget Size" to "Sichtbare Widget-Größe",
    "Corner Radius" to "Eckenradius",
    "Border" to "Rahmen",
    "Background Presets" to "Hintergrundvorlagen",
    "Start" to "Anfang",
    "End" to "Ende",
    "Widget Font" to "Widget-Schrift",
    "Serif" to "Serifenschrift",
    "Serif Bold" to "Serifenschrift fett",
    "Sans" to "Sans-Serif",
    "Monospace" to "Monospace",
    "Quote Font Size" to "Quote-Schriftgröße",
    "Author Font Size" to "Autor-Schriftgröße",
    "Colors" to "Farben",
    "Quote Text" to "Quote-Text",
    "Violet" to "Violett",
    "Amber" to "Bernstein",
    "Green" to "Grün",
    "Blue" to "Blau",
    "Midnight" to "Mitternacht",
    "Ocean" to "Ozean",
    "Emerald" to "Smaragd",
    "Rose" to "Rosé",
    "Sunset" to "Sonnenuntergang",
    "Gold" to "Gold",
    "Slate" to "Schiefer",
    "Paper" to "Papier",
    "Pure Black" to "Tiefschwarz",
    "QUOTE" to "ZITAT",
    "App Info" to "App-Info",
    "Data Health" to "Datenzustand",
    "Actions" to "Aktionen",
    "Next Quote" to "Nächstes Quote",
    "Send Test Notification" to "Testbenachrichtigung senden",
    "Sync Community Quotes" to "Community-Quotes synchronisieren",
    "Refresh Review Statuses" to "Prüfstatus aktualisieren",
    "Verify Quote Database" to "Quote-Datenbank prüfen",
    "No daily quote loaded" to "Kein tägliches Quote geladen",
    "Close Developer Options" to "Entwickleroptionen schließen",
    "Build Type" to "Build-Typ",
    "DB Quotes" to "Datenbank-Quotes",
    "Theme" to "Design",
    "Low Perf Mode" to "Energiesparmodus",
    "Notification" to "Benachrichtigung",
    "Daily Quote" to "Tägliches Quote",
    "Category" to "Kategorie",
    "Bundled" to "Mitgeliefert",
    "Personal" to "Persönlich",
    "Pending reviews" to "Ausstehende Prüfungen",
    "Source mode" to "Quellenmodus",
    "Initial sync" to "Erste Synchronisierung",
    "Verification" to "Prüfung",
    "Empty categories" to "Leere Kategorien",
    "On" to "An",
    "Off" to "Aus",
    "Finished" to "Abgeschlossen",
    "Waiting" to "Wartet",
    "Passed" to "Bestanden",
    "Needs attention" to "Prüfung nötig",
    "Check for app and community quote updates." to "Nach App- und Community-Updates suchen.",
    "Checking for updates…" to "Updates werden gesucht …",
    "You're on the latest version." to "Du verwendest die neueste Version.",
    "Version" to "Version",
    "Could not reach update server" to "Der Update-Server ist nicht erreichbar",
    "Download failed" to "Download fehlgeschlagen",
    "Copy" to "Kopieren",
    "Share" to "Teilen",
    "Favorite" to "Favorit",
    "Delete" to "Löschen",
    "Empty" to "Leer",
    "Create Quote" to "Quote erstellen",
    "Submitted for review" to "Zur Prüfung eingereicht",
    "Back" to "Zurück",
    "Filter Categories" to "Kategorien filtern",
    "Search" to "Suchen",
    "Clear Search" to "Suche löschen",
    "Export Backup" to "Sicherung exportieren",
    "Import Backup" to "Sicherung importieren",
    "Daily Reminders" to "Tägliche Erinnerungen",
    "Daily Reminder scheduled! ✦" to "Tägliche Erinnerung geplant! ✦",
    "Notifications permission is required to receive daily quotes." to "Für tägliche Quotes ist die Benachrichtigungsberechtigung erforderlich.",
    "Daily Reminder disabled" to "Tägliche Erinnerung deaktiviert",
    "Low Performance Mode enabled" to "Energiesparmodus aktiviert",
    "Standard performance mode active" to "Standardleistung aktiv",
    "Backup exported successfully! ✦" to "Sicherung erfolgreich exportiert! ✦",
    "Developer mode enabled" to "Entwicklermodus aktiviert",
    "Widget created" to "Widget erstellt",
    "The happiness of your life depends upon the quality of your thoughts." to "Das Glück deines Lebens hängt von der Qualität deiner Gedanken ab."
)

private val germanCategories = mapOf(
    "Inspirational" to "Inspiration",
    "Community" to "Community",
    "Local" to "Lokal",
    "Reflections" to "Gedanken",
    "Life" to "Leben",
    "Love" to "Liebe",
    "Wisdom" to "Weisheit",
    "Happiness" to "Glück",
    "Optimism" to "Optimismus",
    "Humor" to "Humor",
    "Philosophy" to "Philosophie",
    "Truth" to "Wahrheit",
    "Death" to "Tod",
    "Poetry" to "Poesie",
    "Writing" to "Schreiben",
    "Books" to "Bücher",
    "Reading" to "Lesen",
    "Knowledge" to "Wissen",
    "Success" to "Erfolg",
    "Courage" to "Mut",
    "Friendship" to "Freundschaft",
    "Nature" to "Natur",
    "Faith" to "Glaube",
    "Freedom" to "Freiheit",
    "Uncategorized" to "Ohne Kategorie"
)

fun localizeUi(english: String, language: String): String =
    if (language == QuoteLanguage.GERMAN) germanUi[english] ?: english else english

@Composable
fun uiText(english: String): String = localizeUi(english, LocalAppLanguage.current)

fun localizedCategory(category: String, language: String): String =
    if (language == QuoteLanguage.GERMAN) germanCategories[category] ?: category else category

@Composable
fun categoryText(category: String): String = localizedCategory(category, LocalAppLanguage.current)

fun formattedQuote(text: String, author: String): String =
    if (author.isBlank()) "\"$text\"" else "\"$text\" — $author"
